version: '3'

services:
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: harem-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated
    # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - harem-network

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: harem-php
    volumes:
      - ./:/var/www/html:delegated
    # ports:
    #   - "9000:9000"
    networks:
      - harem-network

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: harem-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer']
    networks:
      - harem-network

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: harem-artisan
    volumes:
      - ./:/var/www/html:delegated
    # depends_on:
    #   - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - harem-network
      
networks:
  harem-network:
    name: harem-network
